__title__ = "trickster"
__author__ = "Bogdan Kulynych, Nikita Samarin"
__email__ = "hello@bogdankulynych.me"
__version__ = "0.2.0"
__copyright__ = "2018 by Bogdan Kulynych (EPFL SPRING Lab)"
__description__ = "Library for attacking machine learning in discrete domains"
__url__ = "https://github.com/spring-epfl/trickster"
__license__ = "MIT"
